spring.application.name=GameService

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gameservice_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configurações JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Porta da aplicação
server.port=8080

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.docker.compose.enabled=false
