spring.application.name=GameService

# Application Port
server.port=8080
# JWT Configuration
jwt.secret=My-secure-secret-key-that-is-at-least-32-characters-Integer
jwt.expiration=86400


# Configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
# spring.datasource.url=jdbc:postgresql://localhost:5432/gameservicedb
spring.datasource.username=${POSTGRES_USER}
#spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
#spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring.jpa.show-sql=true
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
spring.jpa.hibernate.ddl-auto=create-drop
# Set the logging level of the root logger
# Options: TRACE, DEBUG, INFO, WARN, ERROR
logging.level.root=INFO

# Naming strategy
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## URLS
igdb.url=https://api.igdb.com/v4/
igdb.client-id=${IGDB_CLIENT_ID}
igdb.client-secret=${IGDB_CLIENT_SECRET}
igdb.auth-url=https://id.twitch.tv/oauth2/token?client_id=${IGDB_CLIENT_ID}&client_secret=${IGDB_CLIENT_SECRET}&grant_type=client_credentials
igdb.game-endpoint=games
igdb.release-dates-endpoint=release_dates
igdb.franchises-endpoint=collections
igdb.age-rating-endpoint=age_ratings
igdb.involved-companies-endpoint=involved_companies
igdb.companies-endpoint=companies
igdb.company-logos-endpoint=company_logos
igdb.covers-endpoint=covers
igdb.genres-endpoint=genres
igdb.themes-endpoint=themes
igdb.player-perspectives-endpoint=player_perspectives
igdb.game-modes-endpoint=game_modes
igdb.game-language-support-endpoint=language_supports
igdb.regions-endpoint=regions
igdb.languages-endpoint=languages
igdb.platforms-endpoint=platforms
igdb.max_requests = 5
