blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Report
    url: https://github.com/AndersonGACFilho/Game-Insight/security/policy
    about: Please report security vulnerabilities privately via the Security Policy.

