spring.application.name=UserService

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/userdb
spring.data.mongodb.database=userdb
spring.data.mongodb.auto-index-creation=true

jwt.secret=My-secure-secret-key-that-is-at-least-32-characters-long
# token expiration time in seconds
jwt.expiration=86400