spring.application.name=UserService

# MongoDB Configuration at the docker-compose level
spring.data.mongodb.uri= ${MONGO_URI}

spring.data.mongodb.database=${MONGO_DB}
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=My-secure-secret-key-that-is-at-least-32-characters-long
jwt.expiration=86400
