spring.application.name=UserService

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/userdb
spring.data.mongodb.database=userdb

jwt.secret=My-secure-secret-key-that-is-at-least-32-characters-long